### ISSUE TITLE
SetUp project on your machine and get the app running

### ISSUE THREAD

**Issue by RavicharanN** [GitHubCommunity-IIITAllahabad/ProfilePortal-Beta#5]
Follow the guidelines in the **Readme.md** file to setup the project on your machine.

Participants need to add the screenshot of the running application to the **_screenshots_** folder and also their details to the **_contributors.json_** file.

 Marks for this issue will be awarded only when the participants add their details to the **contributors.json** file along with the screenshot of the running application

**Comment by swaager** [comment]
I want to work on this issue

**Comment by RavicharanN** [comment]
Sure, you can proceed directly. This particular issue is open for everyone and won't be closed until opencode ends.

**Comment by Divy123** [comment]
![screenshot from 2018-01-17 03-38-00](https://user-images.githubusercontent.com/31225007/35014845-2ee23934-fb38-11e7-8afe-9526c4086d7d.png)
