### ISSUE TITLE
Add a script to scrape dynamic data from hackerearth

### ISSUE THREAD

**Issue by RavicharanN** [GitHubCommunity-IIITAllahabad/ProfilePortal-Beta#8]
Write a script that scrapes the dynamic user data (Problems Solved, Rating ...etc) from hackerearth.

Add the script to the root of the project with the name _**hackerearth.py**_. Integration of that script into the application will be done after it is tested.

**Note:** Since the data is dynamic and **_might_** require a few other modules along with beautiful soup for scraping, you are requested to specify the modules used.

**Comment by aadixiiita** [comment]
I would like to work on this issue ...

**Comment by RavicharanN** [comment]
Sure @aadixiiita , you can get started. 
Few points before you proceed : 

1. For now, create a folder with the name **_scripts_** and add your script to that folder specifying the modules used. The integration into the application will be done later.

2. Also note that the script submitted cannot be specific to one particular browser. 

Keep us updated on the progress and you can always contact the admins in case of any queries.
